---
version: 2
jobs:
  test:
    docker: &docker
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
            - v1-{{checksum ".circleci/config.yml"}}
            - v1
      - run: yarn
      - save_cache:
          key: v1-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn
      - run: yarn run lint
      - run: yarn run test
      - run: |
          npx nyc report --reporter text-lcov > coverage.lcov
          curl -s https://codecov.io/bash | bash
  pack:
    docker: *docker
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache
      - run: yarn run pack
      - persist_to_workspace:
          root: ./dist
          paths:
            - "**/*"
  publish:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: ./dist
      - run: |
          go get github.com/tcnksm/ghr
          ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_TAG} ./dist/
workflows:
  version: 2
  regular:
    jobs:
      - test
  release:
    jobs:
      - test:
          filters: &tagged-only
            tags:
              only: /.+/
            branches:
              ignore: /.*/
      - pack: 
          requires:
            - test
          filters:
            <<: *tagged-only
      - publish:
          requires:
            - pack
          filters:
            <<: *tagged-only
